name: wordpress
icon: wordpress
title: WordPress

services:
- name: php
  title: PHP
  service: wordpress-php
  required: true
  options:
  - version: '8.3'
    default: true
  - version: '8.2'
  - version: '8.1'  
  derivatives:
  - name: sshd
    service: wordpress-php-sshd
  containers:
  - name: php
    env:
    - name: PHP_MEMORY_LIMIT
      value: 512M
#     resources:
#       request:
#         cpu: 100
#         memory: 16
  volumes:
  - name: wp-content
    size: 20
  links:
  - name: db
    service: mariadb
  - name: wp-content
    service: wp-content-nfs

- name: wp-content-nfs
  title: WP content NFS
  service: nfs-ganesha
  volumes:
  - name: export
    size: 25

- name: nginx
  title: Nginx
  service: wordpress-nginx
  required: true
  links:
  - name: backend
    service: php

- name: mariadb
  title: MariaDB
  service: mariadb
  volumes:
  - name: data
    size: 10

- name: redis
  required: false
  title: Redis
  service: redis

- name: cloud-mariadb
  title: Cloud MariaDB
  service: cloud-mariadb
  disabled: true
  options:
  - version: '10.3'

- name: cloud-mysql
  title: Cloud MySQL
  service: cloud-mysql
  disabled: true
  options:
  - version: '5.7'
  - version: '8'
